site:
  title: devonfw
  url: https://devonfw.com
content:
  sources: 
  - url: https://github.com/devonfw/java
    branches: HEAD
    start_path: devon4j
ui: 
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
urls: 
  latest_version_segment: current
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en]
asciidoc:
  extensions:
  - "./extensions/tabs.js" 
  - "asciidoctor-external-callout"
  - asciidoctor-kroki
